# Generated by Django 4.2.13 on 2024-07-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_utilisateur_is_mentee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=5),
        ),
    ]
